config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users , only: [:create, :new,  :destroy, :show, :update, :edit]
  resource :sessions, only: [:new, :create, :destroy]
  resources :bands

# root to: redirect('/users')

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/band.rb
class Band < ApplicationRecord
  validates :name,  presence: true


end

app/models/user.rb
class User < ApplicationRecord
  validates :e_mail, :password_digest, :session_token, presence: true
  validates :password, length:{minimum: 6, allow_nil: true}

  after_initialize :ensure_session_token






  attr_reader :password

  def self.generate_session_token
    SecureRandom::urlsafe_base64(16)
  end

  def ensure_session_token
    self.session_token ||= User.generate_session_token
  end
  def reset_session_token!
    self.session_token = User.generate_session_token
    self.save
    self.session_token
  end

  def password=(password)
    @password = password
    self.password_digest=BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def self.find_by_credentials(email, password)
    user=User.find_by(e_mail: email)
    if (user)
      return user if (user.is_password?(password))
    else
      return nil
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

helper_method :current_user, :logged_in?

  def current_user
    return nil if session[:session_token].nil?
    @current_user ||= User.find_by(session_token: session[:session_token])

  end

  def logged_in?
    return nil if session[:session_token].nil?
    !User.find_by(session_token: session[:session_token])
  end

  def log_in_user!(user)
    # user.reset_session_token!
    session[:session_token] = user.reset_session_token!
  end



end



#current_user to return the current user.
#logged_in? to return a boolean indicating whether someone is signed in.
#log_in_user!(user) reset the users session token and cookie

app/controllers/bands_controller.rb
class BandsController < ApplicationController

  def index
  end


  def create
    band=Band.new(bands_params)
    if ( band.save)
      redirect_to bands_url
    else
      flash[:error]=band.errors.full_messages
      render :new
    end
  end


  def new
    render :new

  end


  def update
    render :new

  end


  def edit
    render :new
  end


  def show
    render :new
  end

  def destroy
    band=Band.find(params[:id])
    if (band.destroy)
      render :index
    else
      flash[:errors]=band.errors.full_messages
      render :index
    end
  end

  private

  def bands_params
    params.require(:band).permit(:name)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
#log in form
  def new
    render :new
  end
#log in
  def create
    user=User.find_by_credentials(params[:user][:e_mail],params[:user][:password])
    if ( user)
      log_in_user!(user)
      redirect_to user_url(id: user.id)
    else
      flash[:errors]=["email/password is wrong"]
      render :new
    end
  end
# log out
  def destroy
    current_user.reset_session_token!
    session[:session_token]=nil
    redirect_to new_sessions_url
  end

  private
  def user_params
    params.require(:user).permit(:e_mail, :password)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    render :new
  end

  def create
    user = User.new(user_params)
    if (user.save)
      log_in_user!(user)

      redirect_to user_url(user)
    else
        flash.now[:errors]=user.errors.full_messages
      render :new
    end
  end

  def update
  end

  private

  def user_params
    params.require(:user).permit(:e_mail, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bands_helper.rb
module BandsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/bands/index.html.erb
<h1> this is the bands index page</h1>
<% if (flash[:errors]) %>
<% flash[:errors].each do |error| %>
<%= error  %>
<% end %>
<% end %>

<% bands=Band.all %>
<span>
<% bands.each do |band| %>
<%= band.name %>
<!--  delete button-->
 <form action="<%= band_url(band) %>" method="post">
  <input type="hidden" name="_method" value="delete">
  <input type="submit" value="Delete this band(!)">

  <input type='hidden' value= "<% form_authenticity_token %>" name='authenticity_token'>

<!-- edit button -->
<form action="<%= edit_band_url(band) %>" method="edit">
 <input type="hidden" name="_method" value="delete">
 <input type="submit" value="Delete this band(!)">

 <input type='hidden' value= "<% form_authenticity_token %>" name='authenticity_token'>


</form>
</span>
<br>
<% end %>

app/views/bands/new.html.erb
<h1>this is a create a band page</h1>

<form action=" <%= bands_url %> " method="post">
  <input type='hidden' value= "<% form_authenticity_token %>" name='authenticity_token'>
  <label> whats your shitty band's shitty band name?</label>
  <input type='text' value='bn' name =band[name]>
  <input type='submit' value='register band'>

</form>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MusicApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>
  <header class= 'site-header'> the miraculously buggy music app

    <% Time.now %>

  <% if current_user %>
  <form class="logout_button" action=" <%= sessions_url %> " method="post">

    <input type='hidden' value= "<%  form_authenticity_token %>" name=authenticity_token>
    <input type='hidden' value='DELETE' name='_method'>
    <input type='submit' value='log out motherfucker'>
  </form>

  <% elsif !(params[:controller] == "sessions" && params[:action] == "new") %>
  <form  class= 'log_in_buttons' action=" <%= sessions_url %>" method="post">

  <input type="hidden" name="authenticity_token" value=" <% form_authenticity_token %> ">

  <input type="text" name="user[e_mail]" value='username'>

  <input type="text" name="user[password]" value='password'>

  <input type="submit"  value="log yo'self in">
  </form>

</header>
<br>
<br>
<br>

  <% end %>


  <body>
    <%= yield %>
  </body>
</html>

app/views/users/index.html.erb
<% users=User.all %>
<% users.each do |user| %>
<%= user.e_mail  %>
<% end %>

app/views/users/new.html.erb
<div>
welcome to the signup page
<ul>
  <% if (flash[:errors]) %>
<% flash[:errors].each do |error|   %>
  <li>
<%= error %>
</li>
<% end %>
<% end %>
</ul>

<form action= "<%= users_url %>" method="post">
<input
type="hidden"
name="authenticity_token"
value=" <%= form_authenticity_token %>" >

<label> email</label>
<input type='text' name='user[e_mail]'>

<label> password</label>
<input type='password' name='user[password]'>

<input type="submit" name="" value="create user">

</form>
</div>

app/views/users/show.html.erb
<h1> this is a show page for one user</h1>
<%=  params[:id] %>
<br>
<%= User.find(params[:id]).e_mail  %>